### ISSUE TITLE
microdnf makecache

### ISSUE THREAD

**Issue by kiwixz** [rpm-software-management/microdnf#104]
Hi, as the initial metadata download is so excruciatingly slow I'd like to cache it in a docker layer.  The makecache command from dnf would be exactly it.

My current workaround is to run `microdnf install microdnf`.  Seems kinda silly, but it works!

**Comment by jrohel** [comment]
I prepared PR with `makecache` command: https://github.com/rpm-software-management/microdnf/pull/105

**Comment by jrohel** [comment]
The "makecache" command was added. PR: https://github.com/rpm-software-management/microdnf/pull/105 was merged into the upstream.
