### ISSUE TITLE
[RFE] add --exclude option

### ISSUE THREAD

**Issue by itewk** [rpm-software-management/microdnf#119]
# Problem

Currently there is no way to exclude packages when doing a `microdnf update -y`. This is a problem because when doing a rootless container build with buildah you can not upgrade the `filesystem` package (https://bugzilla.redhat.com/show_bug.cgi?id=1708249#c31). Which means. If you want to upgrade all the packages in your container as part of your rootless buildah build, except for the one package (`filesystem`) that you can't, the only way to do it currently is use microdnf to installl dnf to then use the `--exlucde` flag on `dnf` to do the package upgrade.

**Comment by j-mracek** [comment]
There is one option: modify or create /etc/dnf/dnf.conf. in section [main] add `excludepkgs=` with packages that you want to exclude
```
[main]
excludepkgs=filesystem
```

**Comment by itewk** [comment]
interesting. thanks @j-mracek i will give that a try

**Comment by j-mracek** [comment]
I believe that the workarround helped. Closing the issue.

**Comment by itewk** [comment]
@j-mracek yep. worked. For anyone else who submbles on this:
```
# IMPORTANT: need to exclude filesystem due to https://bugzilla.redhat.com/show_bug.cgi?id=1708249#c31
RUN printf "[main]\nexcludepkgs=filesystem" > /etc/dnf/dnf.conf && \
    microdnf update -y && \
    microdnf clean all
```
