### ISSUE TITLE
Unable to make cache with reposdir option disabled 

### ISSUE THREAD

**Issue by ivanov17** [rpm-software-management/microdnf#128]
Hello! 

I need to make cache before container image building as an unprivileged user, because then I can use a cache directory with multiple containers by mounting it with `buildah`, like this:

```
buildah run --volume /home/user/dnf:/var/cache/dnf:O fedora-working-container -- dnf \
    --assumeyes --setopt="install_weak_deps=False" install nginx
```

Because I build my container images from different CentOS/Fedora base images, I need to disable the system repositories and add the required repos to make the cache. 

With `dnf` it works fine:

```
dnf --setopt="reposdir=" --setopt="cachedir=${HOME}/dnf" --assumeyes \
    --repofrompath="fedora,https://archives.fedoraproject.org/pub/fedora/linux/releases/37/Everything/x86_64/os/" \
    --repofrompath="updates,https://archives.fedoraproject.org/pub/fedora/linux/updates/37/Everything/x86_64/" \
    --releasever="37" --repo="fedora,updates" makecache --timer
```

But `microdnf` doesn't have these options. I've tried using similar configuration options in the command line, to no avail:

```
microdnf --setopt="reposdir=" --setopt="cachedir=${HOME}/yum" --assumeyes \
    --setopt="fedora.baseurl=https://archives.fedoraproject.org/pub/fedora/linux/releases/37/Everything/x86_64/os/" \
    --setopt="updates.baseurl=https://archives.fedoraproject.org/pub/fedora/linux/updates/37/Everything/x86_64/" \
    --setopt="fedora.enabled=1" --setopt="updates.enabled=1" --releasever="37" makecache
```

It says that no repodir is set, creates the required directories, but makes no cache:

```
(microdnf:250): libdnf-WARNING **: 21:56:32.942: no repodir set
Metadata cache created.
```
```
ls -l /home/user/yum/*
/home/user/yum/lock:
total 0

/home/user/yum/metadata:
total 0

/home/user/yum/solv:
total 0

```

If I use the `--enablerepo` option, the command returns an error:  

```
microdnf --setopt="reposdir=" --setopt="cachedir=${HOME}/yum" --setopt="fedora.baseurl=https://archives.fedoraproject.org/pub/fedora/linux/releases/37/Everything/x86_64/os/" --setopt="fedora.enabled=1" --enablerepo="fedora" --assumeyes  --releasever="37" makecache

(microdnf:273): libdnf-WARNING **: 23:02:15.730: no repodir set
error: repo fedora not found
```

It looks like `microdnf` doesn't want to use repository URL if it doesn't have section header in the configuration or *.repo files.

I think this issue should be fixed because it disables one of the useful methods of building container images with the `buildah` tool.

Also, it's not possible to use dnf to making cache for microdnf because they have different cache directory hierarchy.

**Comment by jan-kolarik** [comment]
Hello, unfortunately this functionality is missing for `microdnf`. But since Fedora 38 there will be `DNF5` and we are planning to implement this option [there](https://github.com/rpm-software-management/dnf5/issues/168) as well.

For more info or discussion please refer to the mentioned link. I am going to close this one.
