### ISSUE TITLE
Is it possible to specify a package version number?

### ISSUE THREAD

**Issue by glenhein** [rpm-software-management/microdnf#133]
Given the command:

microdnf install -y java-11-openjdk-headless

I'd like to specify a specific version, such as https://rpmfind.net/linux/RPM/opensuse/ports/tumbleweed/aarch64/java-11-openjdk-headless-11.0.19.0-1.2.aarch64.html

Does microdnf support this, and if so, what is the syntax?

Thanks

**Comment by jan-kolarik** [comment]
Hi, if you want to install specific version of package available in any connected repositories, you can use NEVRA format for that, like this:

```
microdnf install java-11-openjdk-headless-1:11.0.19.0.7-1.fc37.x86_64
```

More about specifying packages is in the [DNF man pages](https://dnf.readthedocs.io/en/latest/command_ref.html#specifying-packages).
