### ISSUE TITLE
dnf builddep like command

### ISSUE THREAD

**Issue by vtolstov** [rpm-software-management/microdnf#15]
I want to use microdnf inside small docker image that used as build container, does it possible to add builddep command to microdnf ?

**Comment by ignatenkobrain** [comment]
Patches are welcomed :)

**Comment by vtolstov** [comment]
Ok, i'm try to understand how to work with microdnf code =)

**Comment by m-blaha** [comment]
Closing in favour of https://github.com/rpm-software-management/microdnf/issues/82
