### ISSUE TITLE
don't "error" if no action required for update

### ISSUE THREAD

**Issue by dustymabe** [rpm-software-management/microdnf#3]
If I already have a package installed, like the git rpm, and I call `microdnf update git`, then I get an error:

```
[root@rpmroot vagrant-sshfs]# microdnf update git
Transaction: 1 packages
git-2.11.0-1.fc26.x86_64 (rawhide)
error: Error running transaction: package git-2.11.0-1.fc26.x86_64 is already installed
[root@rpmroot vagrant-sshfs]# echo $?
1
[root@rpmroot vagrant-sshfs]# rpm -q microdnf 
microdnf-1-1.fc26.x86_64
[root@rpmroot vagrant-sshfs]# rpm -q git
git-2.11.0-1.fc26.x86_64
```

We should probably give a "nothing to do" message with no "error"

**Comment by ignatenkobrain** [comment]
this message coming from libdnf, so I think we should add there something like `DNF_GOAL_EMPTY` and then print here `Nothing to do.`
