### ISSUE TITLE
Can microdnf use rhui for yum package installations?

### ISSUE THREAD

**Issue by karthik101** [rpm-software-management/microdnf#32]
I've built RHEL 7 docker atomic image with rh-amazon-rhui-client, with added yum repos and certificates from the host (AWS RHEL7). but microdnf isn't working as expected.  rh-amazon-rhui-client works very well in standard rhel7 docker image.

bash-4.2# microdnf install vim

(process:5): librhsm-WARNING **: Found 0 entitlement certificates

(process:5): librhsm-WARNING **: Found 0 entitlement certificates
Downloading metadata...

(microdnf:5): libdnf-WARNING **: Skipping refresh of rhui-REGION-client-config-server-7: cannot update repo 'rhui-REGION-client-config-server-7': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://rhui2-cds01.REGION.aws.ce.redhat.com/pulp/mirror/rhui-client-config/rhel/server/7/x86_64/os [Could not resolve host: rhui2-cds01.REGION.aws.ce.redhat.com; Name or service not known]
Downloading metadata...

(microdnf:5): libdnf-WARNING **: Skipping refresh of rhui-REGION-rhel-server-releases: cannot update repo 'rhui-REGION-rhel-server-releases': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://rhui2-cds01.REGION.aws.ce.redhat.com/pulp/mirror/content/dist/rhel/rhui/server/7/7Server/x86_64/os [Could not resolve host: rhui2-cds01.REGION.aws.ce.redhat.com; Name or service not known]
Downloading metadata...

(microdnf:5): libdnf-WARNING **: Skipping refresh of rhui-REGION-rhel-server-rh-common: cannot update repo 'rhui-REGION-rhel-server-rh-common': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://rhui2-cds01.REGION.aws.ce.redhat.com/pulp/mirror/content/dist/rhel/rhui/server/7/7Server/x86_64/rh-common/os [Could not resolve host: rhui2-cds01.REGION.aws.ce.redhat.com; Name or service not known]
error: No package matches 'vim'

**Comment by Atchuu** [comment]
We had to do some extra work to have our entitlements available to microdnf. Can you one of the following?

1) Make sure you are using the RH docker package as it contains a patch that will auto-mount some host folders for your entitlements. (This unfortunately means you will lose some of the newer features of the docker client, as it seems to be about 1-1.5 years behind the upstream)
It auto-mounts the following:
```
/run/secrets/etc-pki-entitlement
/run/secrets/rhsm rhsm
```
which then need to be sym-linked into the folders mentioned below

OR

2) Mount the following folders manually from your subscribed/attached host into the container.

```
/etc/pki/entitlement
/etc/rhsm
```

All the repos will be automatically disabled, so you will need to either enable them during your build/run or do what we do and explicitly enable them as needed:
```
microdnf install -y --enablerepo=rhel-7-server-rpms <package>
```

**Comment by Atchuu** [comment]
See this [link](https://github.com/projectatomic/docker/tree/docker-1.13.1-rhel#add-rhel-super-secrets-patchpatch)

**Comment by Atchuu** [comment]
I want to clarify, I don't think you shouldn't just copy those files/folders in, as that probably breaks your licensing agreement with RedHat, and we didn't need to copy in the RH repos, as they auto-populated in a disabled state at build/runtime.

**Comment by dmach** [comment]
We currently have different priorities (mainly get the dnf5 stack working), I don't think we'll work on anything related to RHUI unless we get a request from Red Hat's customer support.
