### ISSUE TITLE
No option to re-install a package

### ISSUE THREAD

**Issue by jtudelag** [rpm-software-management/microdnf#34]
Currently microdnf does not implement any option to reinstall a package. So let's say someone removes a file installed by a given package.

The only option to re-install it, would be to remove it with rpm and run a microdnf install again.
IMHO adding  "reinstall" or "install --force"  would be a good approach.

**Comment by esamattis** [comment]
For anyone coming from google the rpm remove goes like this

```
rpm --erase --nodeps tzdata && microdnf install tzdata
```

I had to do this to fix broken [tzdata package](https://bugzilla.redhat.com/show_bug.cgi?id=1668185) on the ubi8 minimal image.

**Comment by jrohel** [comment]
OK. I started work on the `reinstall` command. PR https://github.com/rpm-software-management/microdnf/pull/61

**Comment by jrohel** [comment]
Command `reinstall` implemented in https://github.com/rpm-software-management/microdnf/pull/61
