### ISSUE TITLE
Add support for excluding of packages from resolution

### ISSUE THREAD

**Issue by Atchuu** [rpm-software-management/microdnf#37]
For containers that have dependencies on things that don't belong in containers, such as systemd.

Similar to the functionality in yum (e.x. yum --exclude=package\* <target_package>), it would be great to be able to exclude them during dependency resolution without having to force remove them via rpm afterwards.

**Comment by jrohel** [comment]
I am working on "excludes" in libdnf.
PR https://github.com/rpm-software-management/libdnf/pull/860

With this patch microdnf/PackageKit/... will automaticaly use excludes from config files (as the DNF does).

**Comment by Conan-Kudo** [comment]
This is now done with the latest release. Enjoy!
