### ISSUE TITLE
why libpeas?

### ISSUE THREAD

**Issue by cgwalters** [rpm-software-management/microdnf#4]
I just don't really see the value of dragging it in here versus just having the command code inline.  We're intentionally trying to keep the command set limited, right?

**Comment by ignatenkobrain** [comment]
> We're intentionally trying to keep the command set limited, right?

the ones which we officially support - yes. It should be very minimal set. Though I don't mind to accept any PR which would implement others (and noting that it is something which can be broken).

**Comment by ignatenkobrain** [comment]
It would make sense to switch for GModule, but I don't really like this idea because then people will have some problems with prototyping their own commands without patching microdnf.

**Comment by dmach** [comment]
The dnf5 version of microdnf (dnf-5-devel branch) is no longer linked with libpeas.
