### ISSUE TITLE
microdnf config files

### ISSUE THREAD

**Issue by shawndwells** [rpm-software-management/microdnf#41]
Hello! Didn't see a mailing list, so opening a ticket to ask for guidance/advice. 

I work on creating US Government configuration baselines for Linux. One of the requirements is to ensure GPG verification of all packages. On classic RHEL/YUM machines this is done by settings in ``/etc/yum.conf``. 

[Looking through the code](https://github.com/rpm-software-management/microdnf/blob/master/dnf/dnf-main.c#L93) it appears microdnf sources configuration from ``/etc/yum.conf.d/*`` and does not use ``/etc/yum.conf``. Is that correct? 

Thanks in advance.

**Comment by shawndwells** [comment]
Asking to ensure all appropriate configuration files are sourced. Microdnf is new to me, so wanted to double check!

**Comment by jrohel** [comment]
Hello.
Microdnf implements only a small subset of YUM/DNF functionality. It was created as a replacement of YUM/DNF to use in small systems without Python.
It reads configuration from repository configuration files "/etc/yum.repos.d/*.repo". But I added reading of global configuration from "/etc/dnf/dnf.conf" (only a subset of options is used) some time ago. But it is not in source code of the microdnf but in the "libdnf" (library used by microdnf). Support for reading variables from environment and directories was also added ( https://github.com/rpm-software-management/libdnf/pull/748 ).

**Comment by Conan-Kudo** [comment]
The upcoming release of MicroDNF will respect `/etc/dnf/dnf.conf` settings if they exist.

**Comment by shawndwells** [comment]
Thanks!

**Comment by pabelanger** [comment]
> The upcoming release of MicroDNF will respect `/etc/dnf/dnf.conf` settings if they exist.

Is this true, which version will have this support? It is unclear if /etc/dnf/dnf.conf is supported today

**Comment by sjkeerthi** [comment]
Recent update of epel-release installation effected due to this of my existing Dockerfile while using  rockylinux:9.2.20230513-minimal

in minimal they use microdnf which I could not able to perform below command using microdnf 

dnf config-manager --set-enabled crb
dnf install epel-release
