### ISSUE TITLE
Support more --setopt= options

### ISSUE THREAD

**Issue by zdzichu** [rpm-software-management/microdnf#46]
Looking at the source, it seems only 'nodocs' flag is supported at all:  https://github.com/rpm-software-management/microdnf/blob/master/dnf/dnf-main.c#L57

Please support other useful flags, for example:
- `install_weak_deps` for skipping non-important dependencies
- `override_install_langs` for ignoring additional languages (saving around 100MiB)

See also https://github.com/rpm-software-management/microdnf/issues/22 (`deltarpm`).

**Comment by jrohel** [comment]
I added these `--setopt=` options during last days:
`--setopt=tsflags=test` https://github.com/rpm-software-management/microdnf/pull/65
`--setopt=install_weak_deps=0/1` https://github.com/rpm-software-management/microdnf/pull/62

The `override_install_langs` option is something new. It is not supported even in DNF. 
Probably there is a possibility to define languages for installing by rpm macro. https://wiki.mageia.org/en/Packaging_localisation_policy But I don't tested it.

**Comment by Conan-Kudo** [comment]
There's an RFE to add this to the DNF stack: [RhBug:1610757](https://bugzilla.redhat.com/show_bug.cgi?id=1610757)

**Comment by ratmice** [comment]
`keepcache` to avoid cleaning the dnf cache is one which would be nice to support.

**Comment by jrohel** [comment]
@ratmice
The `keepcache` option affects whether downloaded / used packages remain in the cache.

I prepared support for `--setopt=keepcache=0/1` PR https://github.com/rpm-software-management/microdnf/pull/98

**Comment by jrohel** [comment]
Support for `--setopt=<option>=<value>` was extended in the microdnf. 

These global option can now be set:
```
install_weak_deps=0/1
allow_vendor_change=0/1
keepcache=0/1
module_platform_id=<name:stream>
cachedir=<path>
reposdir=<path1>,<path2>,...
tsflags=nodocs/test
varsdir=<path1>,<path2>,...
```
All repositories options used by microdnf can be overrided by:
`--setopt=repo_id.option_name=<value>`

I'm not sure if we will add more `--setopt` options to microdnf. We are working on a new project  "DNF5" with a new fullfeatured "microdnf".

**Comment by mglantz** [comment]
Soo... how about:
--setopt=username and --setopt=password :)

The usecase is automatic builds of Red Hat UBI images, when the RPM repository is a private Artifactory repository.

Eg, allowing something like this
```
dnf install -y --setopt=username=${USERNAME} --setopt=password=${PASSWORD} update
```

**Comment by jrohel** [comment]
@mglantz
Hello. I have an idea.
Some time ago I create PR "I extend `-setopt` to support repository options" https://github.com/rpm-software-management/microdnf/pull/95 . 

Usage:
`--setopt=<repo_id>.<option_name>=<value>`
`repo_id` can be a glob pattern.

So, `"--setopt=*.username=${USERNAME}"  "--setopt=*.password=${PASSWORD}"` can be used to set username and password for all repositoies.

**Comment by mglantz** [comment]
That is just excellent! Thanks @jrohel
