### ISSUE TITLE
unable to microdnf clean all on fedora-minimal image

### ISSUE THREAD

**Issue by boydkelly** [rpm-software-management/microdnf#49]
Hi, I recently migrated to a new laptop with silverblue. On my previous machine I was sucessfully building some containers FROM fedora-minimal. However now I get some real strangeness. There seems to be no dnf.conf file in the image. (Not sure if this was the case previously) I can’t run either a microdnf clean all or a rm -rf /var/cache/yum. The message that the directory is empty should not be an issue with rm -rf, and in addition, the directory is empty

```
podman run -it fedora-minimal bash

(microdnf install procps-ng or whatever)

bash-5.0# microdnf clean all

(process:109): libdnf-WARNING **: 09:11:01.916: Loading “/etc/dnf/dnf.conf”: IniParser: Can’t open file
error: failed to remove /var/cache/yum/metadata/fedora-30-x86_64/gpgdir

(microdnf:109): libdnf-WARNING **: 09:11:01.919: held lock metadata at shutdown
bash-5.0# rm -rf /var/cache/yum/
rm: cannot remove ‘/var/cache/yum/metadata/fedora-30-x86_64/gpgdir’: Directory not empty
rm: cannot remove ‘/var/cache/yum/metadata/fedora-modular-30-x86_64/gpgdir’: Directory not empty
rm: cannot remove ‘/var/cache/yum/metadata/updates-30-x86_64/gpgdir’: Directory not empty
rm: cannot remove ‘/var/cache/yum/metadata/updates-modular-30-x86_64/gpgdir’: Directory not empty
bash-5.0# ls -ls /var/cache/yum//metadata/fedora-30-x86_64/gpgdir/
total 0
bash-5.0#

```

**Comment by j-mracek** [comment]
Due to provided output from `rm -rf /var/cache/yum/`, it cannot be a problem in microdnf, but in file system of podman. Unlike Bugzilla the issue cannot be redirected to another component therefore I am closing it.
