### ISSUE TITLE
support for app modules

### ISSUE THREAD

**Issue by jmtd** [rpm-software-management/microdnf#75]
in RHEL 8, `dnf` supports modules e.g.

    dnf module enable maven

but microdnf does not. It would be good if it could!

**Comment by jmtd** [comment]
Has anyone any further thoughts on this?

**Comment by j-mracek** [comment]
I have a good news, we have a plan to implement the support of modules for microdnf. So far I am unable to provide a date but the functionality is related to dnf-5 that was planned for Fedora 34.

**Comment by jmtd** [comment]
Fab thanks!

**Comment by jrohel** [comment]
Microdnf has been extended to support the "module enable", "module disable" and "module reset" commands.
The PR from @j-mracek https://github.com/rpm-software-management/microdnf/pull/85

**Comment by jkroepke** [comment]
Is #85 part of the RHEL 8.3 release?

**Comment by jmtd** [comment]
RHEL 8.3 carries microdnf 3.4.0-1.el8 in BaseOS, which was tagged on 15 Jan.
#85 landed on 5 Nov., so RHEL 8.3 doesn't yet have this. This got into 3.5.0.

The next question is if/when will RHEL 8.3 get this? :)

**Comment by jkroepke** [comment]
@jmtd I figure out, it's just the CLI options.

By create a file like:
```
# /etc/dnf/modules.d/nginx.module
[nginx]
name=nginx
stream=1.18
profiles=
state=enabled
```
I could use the 1.18 nginx stream with ubi on 8.3 images. Thats good enough for me.

> The next question is if/when will RHEL 8.3 get this? :)

From my experiance, i guess in 8.4

**Comment by jmtd** [comment]
> From my experiance, i guess in 8.4

We might have to explicitly request this for it to happen.  I’m going to look into it internally.

**Comment by jrohel** [comment]
As far as I know, the plan is that PR https://github.com/rpm-software-management/microdnf/pull/85 ("module enable", "module disable" and "module reset" commands) will be part of RHEL 8.4.

**Comment by j-mracek** [comment]
The implementation was merged, therefore I can close it as resolved.
