### ISSUE TITLE
Missing or old version check on libdnf with current release

### ISSUE THREAD

**Issue by pejorativefox** [rpm-software-management/microdnf#78]
When building the most recent release of microdnf (0.47.0) with an older version of libdnf (0.39.1) no check is seemingly made to ensure the library is up to date and functional. Building with the older version leads to link time errors. Hoping for it to fail during the cmake configure with an error that the version is not sufficient.

I finally got a good build of it, but it was just incidental, I just upgraded the dnf/libdnf/libsolv packages and thought "I wonder if this would fix that linker error". I had previously assumed i was compiling libdnf missing some features, but with current stable builds of all the deps i get a clean complile.

The version check either needs to be implemented or incremented.

I get this is a niche case and there are likely not a lot of non-distro-vendors building this, but I banged my head on the wall a bit on this one. I have a source built fledgling distro I work on that's rpm/dnf based and this package was nice to keep the install iso small.

**Comment by Conan-Kudo** [comment]
This should be fixed now with microdnf 3.5.1.
