### ISSUE TITLE
microdnf fails if /etc/pki/rpm-gpg does not exist

### ISSUE THREAD

**Issue by Conan-Kudo** [rpm-software-management/microdnf#91]
When trying to do an openSUSE image build with microdnf, I got a failure with the error: `error: Error opening directory ?/etc/pki/rpm-gpg?: No such file or directory`

None of the repositories configured in the image build are doing GPG key verification, so this shouldn't be a failure in that case.

**Comment by Conan-Kudo** [comment]
Here's a sample full build log: [opensuse-tumbleweed-microdnf-container.log.txt](https://github.com/rpm-software-management/microdnf/files/5596894/opensuse-tumbleweed-microdnf-container.log.txt)

**Comment by Conan-Kudo** [comment]
And this is the image build definition being used: https://build.opensuse.org/package/show/home:Pharaoh_Atem:DNF_SUSE:Tumbleweed/opensuse-tumbleweed-microdnf-image

cc: @schaefi, @davidcassany

**Comment by dmach** [comment]
It's easily reproducible in fedora:33 container by (re)moving /etc/pki/rpm-gpg.

**Comment by jrohel** [comment]
The problem can be fixed in libdnf. I will prepare a fix.

**Comment by jrohel** [comment]
Resolved in libdnf PR https://github.com/rpm-software-management/libdnf/pull/1097 .
